Repository EveGroup/EveHolder, pull requests merged in 2020-11, with the labels that each got.

#32 Iteration3 prefilled
  eve_holder/forms.py
  eve_holder/urls.py
  eve_holder/views.py
  templates/eve_holder/event_detail.html
  templates/eve_holder/event_registration.html
Labels: enhancement, implememts

#39 Iteration3
  .github/workflows/django.yml
  eve_holder/forms.py
  eve_holder/models.py
  eve_holder/urls.py
  eve_holder/views.py
  static/css/main.css
  templates/eve_holder/dashboard.html
  templates/eve_holder/event.html
  templates/eve_holder/event_detail.html
  templates/eve_holder/event_registration.html
  templates/eve_holder/events.html
  templates/eve_holder/homepage.html
  templates/eve_holder/login.html
  templates/eve_holder/navbar.html
  templates/eve_holder/visitor.html
  templates/eve_holder/visitor_info.html
  templates/eve_holder/visitors_list.html
Labels: design, enhancement, implememts, security

#43 Iteration4 frontend
  .github/workflows/django.yml
  eve_holder/forms.py
  eve_holder/tests.py
  eve_holder/tests/__init__.py
  eve_holder/tests/test_auth.py
  eve_holder/tests/test_event_models.py
  eve_holder/tests/test_index_page.py
  static/css/homepage.css
  static/css/main.css
  static/images/logo_transparent.png
  templates/eve_holder/event_detail.html
  templates/eve_holder/homepage.html
  templates/eve_holder/navbar.html
Labels: design, unittest

#58 Fixing CI
  .circleci/config.yml
  .github/workflows/django.yml
  .travis.yml
  mysite/settings.py
Labels: unittest

#67 Iteration6 fix ci
  .circleci/config.yml
  .travis.yml
  README.md
  eve_holder/management/commands/group.py
  eve_holder/models.py
  eve_holder/urls.py
  requirements.txt
Labels: unittest

#70 Iteration6 review code
  .circleci/config.yml
  Pipfile
  Pipfile.lock
  README.md
  auth_users.json
  eve_holder/decorations.py
  eve_holder/filters.py
  eve_holder/forms.py
  eve_holder/models.py
  eve_holder/views.py
  mysite/sample.env
  mysite/settings.py
  requirements.txt
  static/css/homepage.css
  static/css/login.css
  static/css/main.css
  static/css/register.css
  static/css/visitor_my_accounts.css
  templates/eve_holder/dashboard.html
  templates/eve_holder/delete.html
  templates/eve_holder/delete_account.html
  templates/eve_holder/event_cancel.html
  templates/eve_holder/event_detail.html
  templates/eve_holder/event_form.html
  templates/eve_holder/event_registration.html
  templates/eve_holder/events.html
  templates/eve_holder/homepage.html
  templates/eve_holder/homepagee.html
  templates/eve_holder/host.html
  templates/eve_holder/host_event_detail.html
  templates/eve_holder/host_my_account.html
  templates/eve_holder/host_update_information.html
  templates/eve_holder/login.html
  templates/eve_holder/messages.html
  templates/eve_holder/navbar.html
  templates/eve_holder/search_event.html
  templates/eve_holder/status.html
  templates/eve_holder/visitor.html
  templates/eve_holder/visitor_info.html
  templates/eve_holder/visitor_my_account.html
  templates/eve_holder/visitor_update_information.html
  templates/eve_holder/visitors_list.html
Labels: documentation, implememts, security, unittest

#71 add modal to delete and logout
  eve_holder/views.py
  templates/eve_holder/host.html
  templates/eve_holder/navbar.html
Labels: design, enhancement

#69 add notification for visitor
  eve_holder/admin.py
  eve_holder/models.py
  eve_holder/urls.py
  eve_holder/views.py
  static/css/main.css
  templates/eve_holder/messages.html
  templates/eve_holder/notifications.html
  templates/eve_holder/visitor.html
Labels: enhancement, implememts

#80 Itration6 heroku
  .circleci/config.yml
  Pipfile
  Pipfile.lock
  Procfile
  mysite/sample.env
  mysite/settings.py
  requirements.txt
  runtime.txt
  static/css/main.css
  static/images/logo.png
  static/images/logo_transparent.png
Labels: implememts
