Repository EveGroup/EveHolder, pull requests merged in 2020-10, with the labels that each got.

#9 starter code
  eve_holder/__init__.py
  eve_holder/admin.py
  eve_holder/apps.py
  eve_holder/migrations/0001_initial.py
  eve_holder/migrations/__init__.py
  eve_holder/models.py
  eve_holder/tests.py
  eve_holder/urls.py
  eve_holder/views.py
  manage.py
  mysite/__init__.py
  mysite/asgi.py
  mysite/settings.py
  mysite/urls.py
  mysite/wsgi.py
  setup.cfg
Labels: enhancement, security, task

#12 Setup format
  eve_holder/apps.py
  eve_holder/models.py
  eve_holder/tests.py
  eve_holder/urls.py
  eve_holder/views.py
  mysite/asgi.py
  mysite/urls.py
  mysite/wsgi.py
Labels: documentation, enhancement

#13 Setup
  .coveragerc
  .github/workflows/django.yml
  eve_holder/__init__.py
  eve_holder/admin.py
  eve_holder/apps.py
  eve_holder/migrations/0001_initial.py
  eve_holder/migrations/__init__.py
  eve_holder/models.py
  eve_holder/tests.py
  eve_holder/urls.py
  eve_holder/views.py
  manage.py
  mysite/__init__.py
  mysite/asgi.py
  mysite/settings.py
  mysite/urls.py
  mysite/wsgi.py
  requirements.txt
  setup.cfg
Labels: documentation, enhancement, help wanted, implememts, security

#23 Iteration1 host backend
  README.md
  eve_holder/admin.py
  eve_holder/forms.py
  eve_holder/models.py
  eve_holder/views.py
  mysite/urls.py
  static/css/main.css
  static/images/KU_Logo_PNG.png
  templates/eve_holder/dashboard.html
  templates/eve_holder/delete.html
  templates/eve_holder/event.html
  templates/eve_holder/event_form.html
  templates/eve_holder/navbar.html
  templates/eve_holder/status.html
  templates/eve_holder/visitor.html
Labels: design, documentation, enhancement, implememts

#24 Iteration1 implements
  eve_holder/urls.py
  eve_holder/views.py
  static/css/homepage.css
  static/css/main.css
  static/images/KU_Logo_PNG.png
  templates/eve_holder/dashboard.html
  templates/eve_holder/delete.html
  templates/eve_holder/home.html
  templates/eve_holder/homepage.html
  templates/eve_holder/login.html
  templates/eve_holder/main.html
  templates/eve_holder/navbar.html
  templates/eve_holder/visitor.html
  templates/eve_holder/visitors.html
Labels: design, implememts

#28 html for visitor to register the event
  templates/eve_holder/event_registration.html
Labels: design, implememts

#30 Implement
  .coveragerc
  .github/workflows/django.yml
  .gitignore
  eve_holder/filters.py
  setup.cfg
  static/css/accounts.css
  templates/eve_holder/login.html
  templates/eve_holder/register.html
Labels: duplicate, enhancement, implememts
